# This is a Dependabot configuration file for automating dependency updates.
# The configuration is set to version 2 of the Dependabot schema.
# It defines update settings for three package ecosystems: GitHub Actions, Bundler, and npm.
# Each ecosystem has its own update configuration, including:
# - The directory to scan for dependencies (root directory in this case).
# - The schedule for checking updates (daily).
# - Allowing both direct and indirect updates for all packages.
# - Grouping updates by ecosystem with specific patterns for version updates.

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    labels:
      - "github-actions"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
