scss_files: '**/*.{scss,css}'

exclude:
  - 'node_modules/**'
  - 'vendor/**'

linters:
  BorderZero:
    enabled: true
    convention: zero

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyRule:
    enabled: true

  ExtendsBeforeMixins:
    enabled: true

  FinalNewline:
    enabled: true

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: lowercase

  ImportPath:
    enabled: true

  ImportantRule:
    enabled: true

  Indentation:
    enabled: true
    character: space
    width: 2

  LeadingZero:
    enabled: true

  MergeableSelector:
    enabled: true

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase

  NestingDepth:
    enabled: true
    max_depth: 3

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    order:
      - display
      - position
      - float
      - clear
      - visibility
      - overflow
      - box-sizing
      - width
      - height

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: true

  SelectorDepth:
    enabled: true
    max_depth: 3

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAroundOperator:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  SpaceBetweenParens:
    enabled: true

  StringQuotes:
    enabled: true
    style: double

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true
