# This GitHub Actions workflow is named "ActionLint".
# It is triggered on push events and manually via the workflow_dispatch event.
#
# Permissions:
# - Read access to repository contents.
# - Write access to pull requests.
#
# Jobs:
# - job-1:
#   - Runs on the latest Ubuntu runner.
#   - Steps:
#     - Harden Runner: Uses the step-security/harden-runner action to audit egress policy.
#     - Checkout: Uses the actions/checkout action to check out the repository.
#     - ActionLint: Uses the devops-actions/actionlint action to lint the workflow files.
#       - Continues on error and sets the ID to action-lint.

name: ActionLint
concurrency:
  group: actionlint-${{ github.ref }}
  cancel-in-progress: false
on:
  push:
    paths:
      - ".github/**"
  pull_request:
    paths:
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: devops-actions/actionlint@ec02b36684b2f574f1d219ad0a43b082e46bf3e4 #v0.1.13
        continue-on-error: true
        id: action-lint
