# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required,
# PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# This GitHub Actions workflow is named 'Dependency Review'.
# It is triggered by pull requests.
#
# Permissions:
# - The workflow has read access to the repository contents.
#
# Jobs:
# - dependency-review:
#   - Runs on the latest Ubuntu runner.
#   - Steps:
#     1. Harden Runner:
#        - Uses the 'step-security/harden-runner' action (version v2.10.4).
#        - Configured with an egress policy set to audit.
#     2. Checkout Repository:
#        - Uses the 'actions/checkout' action (version v4.2.2) to check out the repository.
#     3. Dependency Review:
#        - Uses the 'actions/dependency-review-action' (version v4.5.0) to perform a dependency review.

name: "Dependency Review"
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: "Checkout Repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: "Dependency Review"
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
