name: Generate File List

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at 00:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate_file_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          # Add any dependencies your script needs here
          # For example: pip install requests

      - name: Run the script
        env:
          GIT_REPO_URL: "https://github.com/${{ github.repository }}" # Use the repository where the action is run
        run: |
          # Execute the python script
          python .vscode/generate_file_list.py --repo_url "$GIT_REPO_URL" --output_file file_list.md

      - name: Update README.md
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const readmePath = 'README.md';
            const fileListPath = 'file_list.md';

            try {
              // Read the contents of README.md
              let readmeContent = fs.readFileSync(readmePath, 'utf8');

              // Read the contents of file_list.md
              const fileListContent = fs.readFileSync(fileListPath, 'utf8');

              // Define start and end markers for the file list section
              const startMarker = '<!-- FILE_LIST_START -->';
              const endMarker = '<!-- FILE_LIST_END -->';

              // Find the start and end positions of the file list section
              const startPosition = readmeContent.indexOf(startMarker);
              const endPosition = readmeContent.indexOf(endMarker);

              // Check if the markers exist in the README.md file
              if (startPosition === -1 || endPosition === -1) {
                console.warn('Start or end markers not found in README.md.  The action will add the markers with the file list to the end of the file.');
                readmeContent += `\n${startMarker}\n${fileListContent}\n${endMarker}\n`;
              } else {
                // Replace the existing file list with the new content
                readmeContent = readmeContent.substring(0, startPosition + startMarker.length) +
                  '\n' + fileListContent + '\n' +
                  readmeContent.substring(endPosition);
              }

              // Write the updated content back to README.md
              fs.writeFileSync(readmePath, readmeContent);
              console.log('Successfully updated README.md');
            } catch (error) {
              console.error('Failed to update README.md:', error);
            }

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update file list in README.md"
          file_pattern: "README.md file_list.md"
